name: Merge Repository Schedule
on:
	pull_request:
		types:
			- opened
			- edited
	schedule:
		- cron: 0 22 * * *

jobs:
	merge_schedule:
		runs-on: ubuntu-latest
		steps:
			- uses: gr2m/merge-schedule-action@v1
			  with:
				merge_method: squash
				time_zone: "Asia/Kolkata"
			  env:
				GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}